---
  - name: replace the source list file
    copy: src=sources.list dest=/etc/apt/sources.list owner=root group=root mode=644 backup=yes
    sudo: yes

  - name: update apt cache
    apt: update_cache=yes
    sudo: yes

  - name: install openjdk 7
    apt: name=openjdk-7-jdk state=latest force=yes
    sudo: yes

  # - name : Select java license
  #   shell: echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
  #   sudo: yes
  #
  # - name: Install Oracle Java7
  #   apt: name=oracle-java7-installer state=latest force=yes
  #   sudo: yes
  #
  # - name: Set Oracle Java as default
  #   apt: name=oracle-java7-set-default state=latest force=yes
  #   sudo: yes
